vulnerabilities:
  # Go binary vulnerabilities - cannot be patched, need upstream fixes
  # These are TEMPORARY suppressions until upstream projects release versions
  # compiled with patched Go stdlib (requires Go 1.24.11+ or 1.25.5+)
  #
  # terraform binary - HashiCorp go-getter arbitrary file read vulnerability
  - id: CVE-2025-8959
    statement: Cannot patch compiled Go binary, using latest available version
  # terraform binary - database/sql Postgres race condition
  - id: CVE-2025-47907
    statement: Cannot patch compiled Go binary, using latest available version
  # terraform-docs binary - crypto/x509 ExtKeyUsageAny policy validation issue
  - id: CVE-2025-22874
    statement: Cannot patch compiled Go binary, using latest available version
  # Go stdlib HostnameError.Error() vulnerability - affects terraform, terraform-docs, tflint, trivy
  - id: CVE-2025-61729
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.25.5+
  # Go stdlib archive/tar unbounded allocation - affects terraform-docs
  - id: CVE-2025-58183
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.24.11+
  # Go stdlib HTTP headers limit - affects terraform-docs
  - id: CVE-2025-58186
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.24.11+
  # Go stdlib name constraint checking - affects terraform-docs
  - id: CVE-2025-58187
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.24.11+
  # sigstore timestamp-authority vulnerability - affects tflint, trivy
  - id: CVE-2025-66564
    statement: Cannot patch compiled Go binary, awaiting upstream release with fixed sigstore lib

  # glob CLI command injection - FALSE POSITIVE for npm
  # npm uses glob as a library, not CLI. The vulnerable -c/--cmd code path is never executed.
  # See: https://github.com/npm/cli/issues/8741
  - id: CVE-2025-64756
    statement: FALSE POSITIVE - npm uses glob library interface, not CLI. Vulnerable code path never executed.

  # node-tar vulnerabilities - npm transitive dependency
  # npm 11.8.0 ships tar@7.5.4, fixes require tar@7.5.7+. No npm release available yet.
  - id: CVE-2026-23745
    statement: npm transitive dependency (tar@7.5.4), awaiting npm release with tar@7.5.7+
  - id: CVE-2026-23950
    statement: npm transitive dependency (tar@7.5.4), awaiting npm release with tar@7.5.7+
  - id: CVE-2026-24842
    statement: npm transitive dependency (tar@7.5.4), awaiting npm release with tar@7.5.7+

  # Go stdlib vulnerabilities - net/url and archive/zip
  # Affects terraform-docs, tflint, trivy, docker-compose
  # Requires upstream releases compiled with Go 1.24.12+ or 1.25.6+
  - id: CVE-2025-61726
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.24.12+ or 1.25.6+
  - id: CVE-2025-61728
    statement: Cannot patch compiled Go binary, awaiting upstream release with Go 1.24.12+ or 1.25.6+

misconfigurations:
  # Base image so root user is ok
  - id: AVD-DS-0002